name: Node.js CI

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*', 'lts/-1', 'lts/-2']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm run lint

      - name: Check formatting
        run: pnpm exec prettier --check .

      - name: Test
        run: pnpm test -- --watchAll=false
        env:
          CI: true

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.node-version }}
          parallel: true

      - name: Test Build
        run: pnpm run build --if-present

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
